version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install requirements
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: pytest

      # Store artifacts
      - store_artifacts:
          path: ./report
