# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest API Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  Pytes-API-Testing:

    runs-on: ubuntu-latest
    env: 
      TOKEN: ${{ secrets.TOKEN}}
      BASE_URL: ${{ vars.BASE_URL}}
      OSAKA: ${{ vars.OSAKA}}
      TOKIO: ${{ vars.TOKIO}}
      NY: ${{ vars.NY}}
      EMAIL: ${{ secrets.EMAIL}}
      PASSWORD: ${{ secrets.PASSWORD}}
      FAVORITES_MESSAGE: ${{ vars.FAVORITES_MESSAGE}}
      PATCHED_FAVORITES_MESSAGE: ${{ vars.PATCHED_FAVORITES_MESSAGE}} 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
                
    - name: Test with pytest
      run: |
        pytest        
          
    - name: Upload Pytest report to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: Pytest-test-report
        path: report